# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-13 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0003_answers_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='formheader',
            name='formNo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formApp.FormList'),
        ),
        migrations.AddField(
            model_name='questions',
            name='formNo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formApp.FormList'),
        ),
    ]
